### ISSUE TITLE
`desired_capacity` value

### ISSUE THREAD

**Issue by ajlanghorn** [deanwilson/tf_autoscaling_bastions#2]
I see adding an additional value for desired_capacity in this module to be of some benefit, but I wanted to open a discussion about it because it's arguably of questionable benefit.

In an ASG where the minimum and maximum values are set, and a healthcheck is also set, the ASG should ensure that the number of instances passing the healthcheck is consistent. However, this relies on second-guessing the behaviour of an ASG. Adding `desired_capacity` at least forces the ASG to ensure that any actions it takes don't interrupt the fact that one (or the value of `desired_capacity` if otherwise set) instance should always be available.

Thoughts?

**Comment by deanwilson** [comment]
I have no driving view on this either way. I'm tempted to let apathy win for now and leave the two current settings as they are but if adding it would make your life a little easier I'm also ok with that.
What I'd really like is terraform to support some way to make resource properties optional to allow proper reuse. 

If you'd like the code added to support it then reopen this issue, otherwise I'll close and come back to it when someone has a more pressing need. Thanks for raising the issue though.
